console.log("actionType")
export const ActionTypes = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    SELECTED_PRODUCTS: 'SELECTED_PRODUCTS',
    REMOVE_SELECTED_PRODUCTS: 'REMOVE_SELECTED_PRODUCTS',
    ADD_TO_CART: "ADD_TO_CART1",
    SET_CART_DATA: "SET_CART_DATA",
    SET_PRODUCT_DATA: "SET_PRODUCT_DATA",
    INCREASE_QUANTITY: "INCREASE_QUANTITY",
    DECREASE_QUANTITY: "DECREASE_QUANTITY",
    GET_CART_DATA: "GET_CART_DATA",
    SET_ERROR: "SET_ERROR",
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    SIGNUP_REQUSET: "SIGNUP_REQUSET",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",
    LOGOUT: "LOGOUT",
    SET_TOKEN: "SET_TOKEN",
    ORDER_DETAIL: "ORDER_DETAIL",
    

}